# inherits settings from https://github.com/Manjaro-Sway/.github/blob/main/.github/settings.yml
_extends: manjaro-contrib/.github
repository:
  homepage: https://gitlab.archlinux.org/archlinux/packaging/packages/mesa.git
# you can extend settings using https://probot.github.io/apps/settings/
